### ISSUE TITLE
Error when using Increment field: The getter 'fieldName' was called on null

### ISSUE THREAD

**Issue by tnaffh** [hukusuke1007/flamingo#12]
### Getting an error while using Increment field

**here is my model:**

```dart

import 'some/packages;


part 'user.flamingo.dart';

class AppUser extends Document<AppUser> {
  @Field()
  String name;
  @Field()
  String username;
  @Field()
  String firstName;
  @Field()
  String lastName;
  @Field()
  String email;
  @Field()
  String phoneNumber;
  @Field()
  String photoUrl;

  @Field()
  Increment<int> newMessagesCount;
  @SubCollection()
  Collection<Token> tokens;

  AppUser(
      {String id,
      DocumentSnapshot snapshot,
      Map<String, dynamic> values})
      : super(
            id: id,
            snapshot: snapshot,
            values: values,
      collectionRef: Flamingo.instance.rootReference.collection('users')) {
    tokens = Collection(this, AppUserKey.tokens.value);
    newMessagesCount = Increment(AppUserKey.newMessagesCount.value);
  }


  @override
  Map<String, dynamic> toData() => _$toData(this);

  @override
  void fromData(Map<String, dynamic> data) => _$fromData(this, data);

  /// Call after create, update, delete.
  @override
  void onCompleted(ExecuteType executeType) {
    newMessagesCount = newMessagesCount.onRefresh();
  }
}

```
**and here is some stacktraces:**

```
I/flutter (19763): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (19763): The following NoSuchMethodError was thrown building StreamBuilder<DocumentSnapshot>(dirty, state:
I/flutter (19763): _StreamBuilderBaseState<DocumentSnapshot, AsyncSnapshot<DocumentSnapshot>>#7e0eb):
I/flutter (19763): The getter 'fieldName' was called on null.
I/flutter (19763): Receiver: null
I/flutter (19763): Tried calling: fieldName
I/flutter (19763): 
I/flutter (19763): The relevant error-causing widget was:
I/flutter (19763):   StreamBuilder<DocumentSnapshot>
I/flutter (19763):   file:///.../../file.dart:151:16
I/flutter (19763): 
I/flutter (19763): When the exception was thrown, this was the stack:
I/flutter (19763): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
I/flutter (19763): #1      _$fromData (package:app/models/user.flamingo.dart:75:65)
I/flutter (19763): #2      AppUser.fromData (package:app/models/user.dart:60:47)
I/flutter (19763): #3      Document.setSnapshot (package:flamingo/src/model/document.dart:125:7)
I/flutter (19763): #4      new Document (package:flamingo/src/model/document.dart:48:9)
I/flutter (19763): #5      new AppUser (package:app/models/user.dart:37:9)
I/flutter (19763): #6      _ChatScreenState.build.<anonymous closure> (package:app/widgets/screens/main/chats/chat_screen.dart:157:29)
I/flutter (19763): #7      StreamBuilder.build (package:flutter/src/widgets/async.dart:525:81)
I/flutter (19763): #8      _StreamBuilderBaseState.build (package:flutter/src/widgets/async.dart:129:48)
I/flutter (19763): #9      StatefulElement.build (package:flutter/src/widgets/framework.dart:4744:28)
I/flutter (19763): #10     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4627:15)
I/flutter (19763): #11     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
I/flutter (19763): #12     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
I/flutter (19763): #13     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2730:33)
I/flutter (19763): #14     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:913:20)
I/flutter (19763): #15     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:302:5)
I/flutter (19763): #16     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
I/flutter (19763): #17     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1055:9)
I/flutter (19763): #18     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:971:5)
I/flutter (19763): #22     _invoke (dart:ui/hooks.dart:251:10)
I/flutter (19763): #23     _drawFrame (dart:ui/hooks.dart:209:3)
I/flutter (19763): (elided 3 frames from dart:async)
I/flutter (19763): 
I/flutter (19763): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (19763): id: null, changeType: DocumentChangeType.added, oldIndex: -1, newIndex: 0 cache: true
I/flutter (19763): id: null, changeType: DocumentChangeType.added, oldIndex: -1, newIndex: 1 cache: true
I/flutter (19763): id: null, changeType: DocumentChangeType.added, oldIndex: -1, newIndex: 2 cache: true
I/flutter (19763): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (19763): The following NoSuchMethodError was thrown building StreamBuilder<DocumentSnapshot>(dirty, state:
I/flutter (19763): _StreamBuilderBaseState<DocumentSnapshot, AsyncSnapshot<DocumentSnapshot>>#7e0eb):
I/flutter (19763): The getter 'fieldName' was called on null.
I/flutter (19763): Receiver: null
I/flutter (19763): Tried calling: fieldName
I/flutter (19763): 
I/flutter (19763): The relevant error-causing widget was:
I/flutter (19763):   StreamBuilder<DocumentSnapshot>
I/flutter (19763):   file:///.../../file.dart:151:16
I/flutter (19763): 
I/flutter (19763): When the exception was thrown, this was the stack:
I/flutter (19763): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
I/flutter (19763): #1      _$fromData (package:app/models/user.flamingo.dart:75:65)
I/flutter (19763): #2      AppUser.fromData (package:app/models/user.dart:60:47)
I/flutter (19763): #3      Document.setSnapshot (package:flamingo/src/model/document.dart:125:7)
I/flutter (19763): #4      new Document (package:flamingo/src/model/document.dart:48:9)
I/flutter (19763): #5      new AppUser (package:app/models/user.dart:37:9)
I/flutter (19763): #6      _ChatScreenState.build.<anonymous closure> (package:app/widgets/screens/main/chats/chat_screen.dart:157:29)
I/flutter (19763): #7      StreamBuilder.build (package:flutter/src/widgets/async.dart:525:81)
I/flutter (19763): #8      _StreamBuilderBaseState.build (package:flutter/src/widgets/async.dart:129:48)
I/flutter (19763): #9      StatefulElement.build (package:flutter/src/widgets/framework.dart:4744:28)
I/flutter (19763): #10     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4627:15)
I/flutter (19763): #11     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
I/flutter (19763): #12     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
I/flutter (19763): #13     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2730:33)
I/flutter (19763): #14     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:913:20)
I/flutter (19763): #15     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:302:5)
I/flutter (19763): #16     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
I/flutter (19763): #17     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1055:9)
I/flutter (19763): #18     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:971:5)
I/flutter (19763): #22     _invoke (dart:ui/hooks.dart:251:10)
I/flutter (19763): #23     _drawFrame (dart:ui/hooks.dart:209:3)
I/flutter (19763): (elided 3 frames from dart:async)
I/flutter (19763): 
I/flutter (19763): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by hukusuke1007** [comment]
Thank you for reporting. I checked it. This is bug.
I will fix it. Maybe, it will take some time. Please use "int" instead of Increment.

**Comment by tnaffh** [comment]
Thank you. I will use int for now.
